### ISSUE TITLE
Unable to parse some literals

### ISSUE THREAD

**Issue by folkvir** [sage-org/sage-jena#10]
**Dataset:**  http://sage.univ-nantes.fr/sparql/dbpedia-2016-04

**Query**: `PREFIX void: <http://rdfs.org/ns/void#> CONSTRUCT {  <http://example.com/void> void:triples ?count } WHERE { SELECT (COUNT(*) AS ?count)  WHERE { ?s ?p ?o } }`

**Error**: `java.lang.StringIndexOutOfBoundsException: String index out of range: -1`

The error appears to be in the parsing of "\@" literals:
```java
else if (literal.contains("\"@")) {
 int index = literal.lastIndexOf("\"@");
 value = NodeFactory.createLiteral(literal.substring(1, index), literal.substring(index + 2));
} 
```

**Stacktrace**: `at java.lang.String.substring(String.java:1967)
	at org.gdd.sage.http.SageDefaultClient.parseNode(SageDefaultClient.java:322)
	at org.gdd.sage.http.SageDefaultClient.lambda$decodeResponse$2(SageDefaultClient.java:355)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870)
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.gdd.sage.http.SageDefaultClient.decodeResponse(SageDefaultClient.java:362)
	at org.gdd.sage.http.SageDefaultClient.sendQuery(SageDefaultClient.java:181)
	at org.gdd.sage.http.SageDefaultClient.query(SageDefaultClient.java:208)
	at org.gdd.sage.engine.iterators.SageBGPIterator.query(SageBGPIterator.java:33)
	at org.gdd.sage.engine.iterators.base.SageQueryIterator.produceBindings(SageQueryIterator.java:54)
	at org.gdd.sage.engine.iterators.base.BufferedIterator.fillBuffer(BufferedIterator.java:31)
	at org.gdd.sage.engine.iterators.base.BufferedIterator.hasNextBinding(BufferedIterator.java:38)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.iterator.QueryIterGroup$1.initializeIterator(QueryIterGroup.java:111)
	at org.apache.jena.atlas.iterator.IteratorDelayedInitialization.init(IteratorDelayedInitialization.java:40)
	at org.apache.jena.atlas.iterator.IteratorDelayedInitialization.hasNext(IteratorDelayedInitialization.java:50)
	at org.apache.jena.sparql.engine.iterator.QueryIterPlainWrapper.hasNextBinding(QueryIterPlainWrapper.java:53)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.iterator.QueryIterProcessBinding.hasNextBinding(QueryIterProcessBinding.java:66)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.iterator.QueryIterConvert.hasNextBinding(QueryIterConvert.java:58)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.atlas.iterator.Iter$2.hasNext(Iter.java:265)
	at org.apache.jena.ext.com.google.common.collect.Iterators$ConcatenatedIterator.getTopMetaIterator(Iterators.java:1319)
	at org.apache.jena.ext.com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1335)
	at org.apache.jena.sparql.engine.QueryExecutionBase.execConstruct(QueryExecutionBase.java:216)
	at org.apache.jena.sparql.engine.QueryExecutionBase.execConstruct(QueryExecutionBase.java:204)
	at org.gdd.sage.cli.ConstructQueryExecutor.evaluate(ConstructQueryExecutor.java:57)
	at org.gdd.sage.cli.ConstructQueryExecutor.execute(ConstructQueryExecutor.java:24)`

**Comment by Callidon** [comment]
Fixed in #11
