### ISSUE TITLE
Jena Riot exception ...

### ISSUE THREAD

**Issue by momo54** [sage-org/sage-jena#7]
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT ?name ?place WHERE {
 ?actor a dbo:Actor . 
 ?actor rdfs:label ?name . 
 OPTIONAL {
   ?actor dbo:birthPlace ?place . 
 }
}

./sage-jena -f query3.sparql -u http://sage.univ-nantes.fr/sparql/dbpedia-2016-04
16:30:10 ERROR exec                      :: org.apache.jena.riot.RiotException: org.apache.jena.riot.RiotException: Trailing characters in string: ""Rags" Ragland"@en

**Comment by momo54** [comment]
Error changed with commit last commit.

Many results, then:
`   <result>
      <binding name="name">
        <literal xml:lang="en">İpek Yaylacıoğlu</literal>
      </Exception in thread "main" java.util.NoSuchElementException: SageBGPIterator
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.nextBinding(QueryIteratorBase.java:154)
	at org.gdd.sage.engine.iterators.base.BlockBufferedIterator.hasNextBinding(BlockBufferedIterator.java:43)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.iterator.QueryIterConvert.hasNextBinding(QueryIterConvert.java:58)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.ResultSetStream.hasNext(ResultSetStream.java:74)
	at org.apache.jena.sparql.engine.ResultSetCheckCondition.hasNext(ResultSetCheckCondition.java:55)
	at org.apache.jena.sparql.resultset.ResultSetApply.apply(ResultSetApply.java:38)
	at org.apache.jena.riot.resultset.rw.ResultSetWriterXML.write(ResultSetWriterXML.java:82)
	at org.apache.jena.riot.resultset.rw.ResultsWriter.write(ResultsWriter.java:127)
	at org.apache.jena.riot.resultset.rw.ResultsWriter.write(ResultsWriter.java:97)
	at org.apache.jena.riot.resultset.rw.ResultsWriter$Builder.write(ResultsWriter.java:71)
	at org.apache.jena.query.ResultSetFormatter.output(ResultSetFormatter.java:320)
	at org.apache.jena.query.ResultSetFormatter.outputAsXML(ResultSetFormatter.java:347)
	at org.apache.jena.query.ResultSetFormatter.outputAsXML(ResultSetFormatter.java:338)
	at org.gdd.sage.cli.SelectQueryExecutor.execute(SelectQueryExecutor.java:26)
	at org.gdd.sage.cli.CLI.main(CLI.java:80)`

**Comment by momo54** [comment]
Fixed
