### ISSUE TITLE
BoundJoinIterator Exception

### ISSUE THREAD

**Issue by momo54** [sage-org/sage-jena#9]
When executing:
```
prefix dbo: <http://dbpedia.org/ontology/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?name ?place WHERE {
 {
  ?actor a dbo:Actor .
  ?actor rdfs:label ?name .
  ?actor dbo:birthPlace ?place 
 } union {
  ?actor a dbo:Actor .
  ?actor rdfs:label ?name 
 }
}
```
with 
`./sage-jena -m q3u.stat --format CSV -f query3u.sparql -u http://sage.univ-nantes.fr/sparql/dbpedia-2016-04 
`
Start running, then got:

```
İlknur Melis Durası,http://dbpedia.org/resourcException in thread "main" java.util.NoSuchElementException: BoundJoinIterator
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.nextBinding(QueryIteratorBase.java:158)
	at org.apache.jena.sparql.engine.iterator.QueryIterConcat.moveToNextBinding(QueryIterConcat.java:108)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.nextBinding(QueryIteratorBase.java:156)
```

**Comment by momo54** [comment]
Fixed in commit 96944e850504258656df887b3c855733e8cceef3
